export type DisplayType =
  | 'inline-block'
  | 'inline-list-item'
  | 'inline-table'
  | 'inherit'
  | 'initial'
  | 'revert'
  | 'unset'
  | 'block'
  | 'inline'
  | 'run-in'
  | 'flow'
  | 'flow-root'
  | 'ruby'
  | 'table'
  | 'none';
