import { CSSProperties } from 'react';
import { ThemeTextType, ColorsType } from '../src/theme/theme.types';

export type TextType = {
  textProps?: ThemeTextType;
  textColor?: ColorsType;
} & Pick<
  CSSProperties,
  | 'textAlign'
  | 'textAlignLast'
  | 'textAnchor'
  | 'textCombineUpright'
  | 'textDecoration'
  | 'textDecorationColor'
  | 'textDecorationLine'
  | 'textDecorationSkip'
  | 'textDecorationSkipInk'
  | 'textDecorationStyle'
  | 'textDecorationThickness'
  | 'textEmphasis'
  | 'textUnderlinePosition'
  | 'textEmphasisColor'
  | 'textEmphasisPosition'
  | 'textEmphasisStyle'
  | 'textIndent'
  | 'textJustify'
  | 'textOrientation'
  | 'textOverflow'
  | 'textRendering'
  | 'textShadow'
  | 'textSizeAdjust'
  | 'textTransform'
  | 'textUnderlineOffset'
  | 'font'
  | 'fontFamily'
  | 'fontFeatureSettings'
  | 'fontKerning'
  | 'fontLanguageOverride'
  | 'fontOpticalSizing'
  | 'fontSizeAdjust'
  | 'fontSmooth'
  | 'fontStretch'
  | 'fontStyle'
  | 'fontSynthesis'
  | 'fontVariant'
  | 'fontVariantAlternates'
  | 'fontVariantCaps'
  | 'fontVariantEastAsian'
  | 'fontVariantLigatures'
  | 'fontVariantNumeric'
  | 'fontVariantPosition'
  | 'fontVariationSettings'
  | 'wordBreak'
  | 'wordSpacing'
  | 'wordWrap'
  | 'fontSize'
  | 'fontWeight'
>;
