export const countriesList = [
  {
    cca2: 'none',
    flag: '',
    idd: 'Select one',
    name: 'Select a country',
  },
  {
    cca2: 'ng',
    flag: 'https://flagcdn.com/ng.svg',
    idd: '234',
    name: 'Nigeria',
  },
  {
    cca2: 'dk',
    flag: 'https://flagcdn.com/dk.svg',
    idd: '45',
    name: 'Denmark',
  },
  {
    cca2: 'bv',
    flag: 'https://flagcdn.com/bv.svg',
    idd: '47',
    name: 'Bouvet Island',
  },
  {
    cca2: 'ro',
    flag: 'https://flagcdn.com/ro.svg',
    idd: '40',
    name: 'Romania',
  },
  {
    cca2: 'nr',
    flag: 'https://flagcdn.com/nr.svg',
    idd: '674',
    name: 'Nauru',
  },
  {
    cca2: 'gn',
    flag: 'https://flagcdn.com/gn.svg',
    idd: '224',
    name: 'Guinea',
  },
  {
    cca2: 'gm',
    flag: 'https://flagcdn.com/gm.svg',
    idd: '220',
    name: 'Gambia',
  },
  {
    cca2: 'tc',
    flag: 'https://flagcdn.com/tc.svg',
    idd: '1649',
    name: 'Turks and Caicos Islands',
  },
  {
    cca2: 'rs',
    flag: 'https://flagcdn.com/rs.svg',
    idd: '381',
    name: 'Serbia',
  },
  {
    cca2: 'sx',
    flag: 'https://flagcdn.com/sx.svg',
    idd: '1721',
    name: 'Sint Maarten',
  },
  {
    cca2: 'vc',
    flag: 'https://flagcdn.com/vc.svg',
    idd: '1784',
    name: 'Saint Vincent and the Grenadines',
  },
  {
    cca2: 'mv',
    flag: 'https://flagcdn.com/mv.svg',
    idd: '960',
    name: 'Maldives',
  },
  {
    cca2: 'uy',
    flag: 'https://flagcdn.com/uy.svg',
    idd: '598',
    name: 'Uruguay',
  },
  {
    cca2: 'is',
    flag: 'https://flagcdn.com/is.svg',
    idd: '354',
    name: 'Iceland',
  },
  {
    cca2: 'ua',
    flag: 'https://flagcdn.com/ua.svg',
    idd: '380',
    name: 'Ukraine',
  },
  {
    cca2: 'bt',
    flag: 'https://flagcdn.com/bt.svg',
    idd: '975',
    name: 'Bhutan',
  },
  {
    cca2: 'mx',
    flag: 'https://flagcdn.com/mx.svg',
    idd: '52',
    name: 'Mexico',
  },
  {
    cca2: 've',
    flag: 'https://flagcdn.com/ve.svg',
    idd: '58',
    name: 'Venezuela',
  },
  {
    cca2: 'cx',
    flag: 'https://flagcdn.com/cx.svg',
    idd: '61',
    name: 'Christmas Island',
  },
  {
    cca2: 'uz',
    flag: 'https://flagcdn.com/uz.svg',
    idd: '998',
    name: 'Uzbekistan',
  },
  {
    cca2: 'tg',
    flag: 'https://flagcdn.com/tg.svg',
    idd: '228',
    name: 'Togo',
  },
  {
    cca2: 'mw',
    flag: 'https://flagcdn.com/mw.svg',
    idd: '265',
    name: 'Malawi',
  },
  {
    cca2: 'tz',
    flag: 'https://flagcdn.com/tz.svg',
    idd: '255',
    name: 'Tanzania',
  },
  {
    cca2: 'by',
    flag: 'https://flagcdn.com/by.svg',
    idd: '375',
    name: 'Belarus',
  },
  {
    cca2: 'aw',
    flag: 'https://flagcdn.com/aw.svg',
    idd: '297',
    name: 'Aruba',
  },
  {
    cca2: 'iq',
    flag: 'https://flagcdn.com/iq.svg',
    idd: '964',
    name: 'Iraq',
  },
  {
    cca2: 'tf',
    flag: 'https://flagcdn.com/tf.svg',
    idd: '262',
    name: 'French Southern and Antarctic Lands',
  },
  {
    cca2: 'to',
    flag: 'https://flagcdn.com/to.svg',
    idd: '676',
    name: 'Tonga',
  },
  {
    cca2: 'hr',
    flag: 'https://flagcdn.com/hr.svg',
    idd: '385',
    name: 'Croatia',
  },
  {
    cca2: 'gs',
    flag: 'https://flagcdn.com/gs.svg',
    idd: '500',
    name: 'South Georgia',
  },
  {
    cca2: 'ye',
    flag: 'https://flagcdn.com/ye.svg',
    idd: '967',
    name: 'Yemen',
  },
  {
    cca2: 'my',
    flag: 'https://flagcdn.com/my.svg',
    idd: '60',
    name: 'Malaysia',
  },
  {
    cca2: 'bl',
    flag: 'https://flagcdn.com/bl.svg',
    idd: '590',
    name: 'Saint Barthélemy',
  },
  {
    cca2: 'ck',
    flag: 'https://flagcdn.com/ck.svg',
    idd: '682',
    name: 'Cook Islands',
  },
  {
    cca2: 'je',
    flag: 'https://flagcdn.com/je.svg',
    idd: '44',
    name: 'Jersey',
  },
  {
    cca2: 'mn',
    flag: 'https://flagcdn.com/mn.svg',
    idd: '976',
    name: 'Mongolia',
  },
  {
    cca2: 'mc',
    flag: 'https://flagcdn.com/mc.svg',
    idd: '377',
    name: 'Monaco',
  },
  {
    cca2: 'au',
    flag: 'https://flagcdn.com/au.svg',
    idd: '61',
    name: 'Australia',
  },
  {
    cca2: 'ec',
    flag: 'https://flagcdn.com/ec.svg',
    idd: '593',
    name: 'Ecuador',
  },
  {
    cca2: 'fi',
    flag: 'https://flagcdn.com/fi.svg',
    idd: '358',
    name: 'Finland',
  },
  {
    cca2: 'mg',
    flag: 'https://flagcdn.com/mg.svg',
    idd: '261',
    name: 'Madagascar',
  },
  {
    cca2: 'ie',
    flag: 'https://flagcdn.com/ie.svg',
    idd: '353',
    name: 'Ireland',
  },
  {
    cca2: 'se',
    flag: 'https://flagcdn.com/se.svg',
    idd: '46',
    name: 'Sweden',
  },
  {
    cca2: 'nz',
    flag: 'https://flagcdn.com/nz.svg',
    idd: '64',
    name: 'New Zealand',
  },
  {
    cca2: 'wf',
    flag: 'https://flagcdn.com/wf.svg',
    idd: '681',
    name: 'Wallis and Futuna',
  },
  {
    cca2: 'om',
    flag: 'https://flagcdn.com/om.svg',
    idd: '968',
    name: 'Oman',
  },
  {
    cca2: 'ag',
    flag: 'https://flagcdn.com/ag.svg',
    idd: '1268',
    name: 'Antigua and Barbuda',
  },
  {
    cca2: 'kn',
    flag: 'https://flagcdn.com/kn.svg',
    idd: '1869',
    name: 'Saint Kitts and Nevis',
  },
  {
    cca2: 'nc',
    flag: 'https://flagcdn.com/nc.svg',
    idd: '687',
    name: 'New Caledonia',
  },
  {
    cca2: 'ws',
    flag: 'https://flagcdn.com/ws.svg',
    idd: '685',
    name: 'Samoa',
  },
  {
    cca2: 'ca',
    flag: 'https://flagcdn.com/ca.svg',
    idd: '1',
    name: 'Canada',
  },
  {
    cca2: 'sg',
    flag: 'https://flagcdn.com/sg.svg',
    idd: '65',
    name: 'Singapore',
  },
  {
    cca2: 'gt',
    flag: 'https://flagcdn.com/gt.svg',
    idd: '502',
    name: 'Guatemala',
  },
  {
    cca2: 'tr',
    flag: 'https://flagcdn.com/tr.svg',
    idd: '90',
    name: 'Turkey',
  },
  {
    cca2: 'np',
    flag: 'https://flagcdn.com/np.svg',
    idd: '977',
    name: 'Nepal',
  },
  {
    cca2: 'li',
    flag: 'https://flagcdn.com/li.svg',
    idd: '423',
    name: 'Liechtenstein',
  },
  {
    cca2: 'ba',
    flag: 'https://flagcdn.com/ba.svg',
    idd: '387',
    name: 'Bosnia and Herzegovina',
  },
  {
    cca2: 'td',
    flag: 'https://flagcdn.com/td.svg',
    idd: '235',
    name: 'Chad',
  },
  {
    cca2: 'bo',
    flag: 'https://flagcdn.com/bo.svg',
    idd: '591',
    name: 'Bolivia',
  },
  {
    cca2: 'ht',
    flag: 'https://flagcdn.com/ht.svg',
    idd: '509',
    name: 'Haiti',
  },
  {
    cca2: 'fo',
    flag: 'https://flagcdn.com/fo.svg',
    idd: '298',
    name: 'Faroe Islands',
  },
  {
    cca2: 'mu',
    flag: 'https://flagcdn.com/mu.svg',
    idd: '230',
    name: 'Mauritius',
  },
  {
    cca2: 'vi',
    flag: 'https://flagcdn.com/vi.svg',
    idd: '1340',
    name: 'United States Virgin Islands',
  },
  {
    cca2: 'ms',
    flag: 'https://flagcdn.com/ms.svg',
    idd: '1664',
    name: 'Montserrat',
  },
  {
    cca2: 'gy',
    flag: 'https://flagcdn.com/gy.svg',
    idd: '592',
    name: 'Guyana',
  },
  {
    cca2: 'mp',
    flag: 'https://flagcdn.com/mp.svg',
    idd: '1670',
    name: 'Northern Mariana Islands',
  },
  {
    cca2: 'lc',
    flag: 'https://flagcdn.com/lc.svg',
    idd: '1758',
    name: 'Saint Lucia',
  },
  {
    cca2: 'id',
    flag: 'https://flagcdn.com/id.svg',
    idd: '62',
    name: 'Indonesia',
  },
  {
    cca2: 'at',
    flag: 'https://flagcdn.com/at.svg',
    idd: '43',
    name: 'Austria',
  },
  {
    cca2: 'gp',
    flag: 'https://flagcdn.com/gp.svg',
    idd: '590',
    name: 'Guadeloupe',
  },
  {
    cca2: 'er',
    flag: 'https://flagcdn.com/er.svg',
    idd: '291',
    name: 'Eritrea',
  },
  {
    cca2: 'kp',
    flag: 'https://flagcdn.com/kp.svg',
    idd: '850',
    name: 'North Korea',
  },
  {
    cca2: 'sc',
    flag: 'https://flagcdn.com/sc.svg',
    idd: '248',
    name: 'Seychelles',
  },
  {
    cca2: 'bd',
    flag: 'https://flagcdn.com/bd.svg',
    idd: '880',
    name: 'Bangladesh',
  },
  {
    cca2: 'bw',
    flag: 'https://flagcdn.com/bw.svg',
    idd: '267',
    name: 'Botswana',
  },
  {
    cca2: 'pm',
    flag: 'https://flagcdn.com/pm.svg',
    idd: '508',
    name: 'Saint Pierre and Miquelon',
  },
  {
    cca2: 'pk',
    flag: 'https://flagcdn.com/pk.svg',
    idd: '92',
    name: 'Pakistan',
  },
  {
    cca2: 'bb',
    flag: 'https://flagcdn.com/bb.svg',
    idd: '1246',
    name: 'Barbados',
  },
  {
    cca2: 'mq',
    flag: 'https://flagcdn.com/mq.svg',
    idd: '596',
    name: 'Martinique',
  },
  {
    cca2: 'nu',
    flag: 'https://flagcdn.com/nu.svg',
    idd: '683',
    name: 'Niue',
  },
  {
    cca2: 'pw',
    flag: 'https://flagcdn.com/pw.svg',
    idd: '680',
    name: 'Palau',
  },
  {
    cca2: 'am',
    flag: 'https://flagcdn.com/am.svg',
    idd: '374',
    name: 'Armenia',
  },
  {
    cca2: 'mm',
    flag: 'https://flagcdn.com/mm.svg',
    idd: '95',
    name: 'Myanmar',
  },
  {
    cca2: 're',
    flag: 'https://flagcdn.com/re.svg',
    idd: '262',
    name: 'Réunion',
  },
  {
    cca2: 'nl',
    flag: 'https://flagcdn.com/nl.svg',
    idd: '31',
    name: 'Netherlands',
  },
  {
    cca2: 'ax',
    flag: 'https://flagcdn.com/ax.svg',
    idd: '35818',
    name: 'Åland Islands',
  },
  {
    cca2: 'cm',
    flag: 'https://flagcdn.com/cm.svg',
    idd: '237',
    name: 'Cameroon',
  },
  {
    cca2: 'pt',
    flag: 'https://flagcdn.com/pt.svg',
    idd: '351',
    name: 'Portugal',
  },
  {
    cca2: 'py',
    flag: 'https://flagcdn.com/py.svg',
    idd: '595',
    name: 'Paraguay',
  },
  {
    cca2: 'cw',
    flag: 'https://flagcdn.com/cw.svg',
    idd: '599',
    name: 'Curaçao',
  },
  {
    cca2: 'hn',
    flag: 'https://flagcdn.com/hn.svg',
    idd: '504',
    name: 'Honduras',
  },
  {
    cca2: 'zw',
    flag: 'https://flagcdn.com/zw.svg',
    idd: '263',
    name: 'Zimbabwe',
  },
  {
    cca2: 'mt',
    flag: 'https://flagcdn.com/mt.svg',
    idd: '356',
    name: 'Malta',
  },
  {
    cca2: 'gg',
    flag: 'https://flagcdn.com/gg.svg',
    idd: '44',
    name: 'Guernsey',
  },
  {
    cca2: 'jp',
    flag: 'https://flagcdn.com/jp.svg',
    idd: '81',
    name: 'Japan',
  },
  {
    cca2: 'so',
    flag: 'https://flagcdn.com/so.svg',
    idd: '252',
    name: 'Somalia',
  },
  {
    cca2: 'gr',
    flag: 'https://flagcdn.com/gr.svg',
    idd: '30',
    name: 'Greece',
  },
  {
    cca2: 'kh',
    flag: 'https://flagcdn.com/kh.svg',
    idd: '855',
    name: 'Cambodia',
  },
  {
    cca2: 'dm',
    flag: 'https://flagcdn.com/dm.svg',
    idd: '1767',
    name: 'Dominica',
  },
  {
    cca2: 'tk',
    flag: 'https://flagcdn.com/tk.svg',
    idd: '690',
    name: 'Tokelau',
  },
  {
    cca2: 'gu',
    flag: 'https://flagcdn.com/gu.svg',
    idd: '1671',
    name: 'Guam',
  },
  {
    cca2: 'gh',
    flag: 'https://flagcdn.com/gh.svg',
    idd: '233',
    name: 'Ghana',
  },
  {
    cca2: 'qa',
    flag: 'https://flagcdn.com/qa.svg',
    idd: '974',
    name: 'Qatar',
  },
  {
    cca2: 'sv',
    flag: 'https://flagcdn.com/sv.svg',
    idd: '503',
    name: 'El Salvador',
  },
  {
    cca2: 'bm',
    flag: 'https://flagcdn.com/bm.svg',
    idd: '1441',
    name: 'Bermuda',
  },
  {
    cca2: 'hk',
    flag: 'https://flagcdn.com/hk.svg',
    idd: '852',
    name: 'Hong Kong',
  },
  {
    cca2: 'pr',
    flag: 'https://flagcdn.com/pr.svg',
    idd: '1787',
    name: 'Puerto Rico',
  },
  {
    cca2: 'sb',
    flag: 'https://flagcdn.com/sb.svg',
    idd: '677',
    name: 'Solomon Islands',
  },
  {
    cca2: 'vg',
    flag: 'https://flagcdn.com/vg.svg',
    idd: '1284',
    name: 'British Virgin Islands',
  },
  {
    cca2: 'cg',
    flag: 'https://flagcdn.com/cg.svg',
    idd: '242',
    name: 'Republic of the Congo',
  },
  {
    cca2: 'no',
    flag: 'https://flagcdn.com/no.svg',
    idd: '47',
    name: 'Norway',
  },
  {
    cca2: 'lv',
    flag: 'https://flagcdn.com/lv.svg',
    idd: '371',
    name: 'Latvia',
  },
  {
    cca2: 'pe',
    flag: 'https://flagcdn.com/pe.svg',
    idd: '51',
    name: 'Peru',
  },
  {
    cca2: 'tm',
    flag: 'https://flagcdn.com/tm.svg',
    idd: '993',
    name: 'Turkmenistan',
  },
  {
    cca2: 'lt',
    flag: 'https://flagcdn.com/lt.svg',
    idd: '370',
    name: 'Lithuania',
  },
  {
    cca2: 'et',
    flag: 'https://flagcdn.com/et.svg',
    idd: '251',
    name: 'Ethiopia',
  },
  {
    cca2: 'md',
    flag: 'https://flagcdn.com/md.svg',
    idd: '373',
    name: 'Moldova',
  },
  {
    cca2: 'sm',
    flag: 'https://flagcdn.com/sm.svg',
    idd: '378',
    name: 'San Marino',
  },
  {
    cca2: 'tl',
    flag: 'https://flagcdn.com/tl.svg',
    idd: '670',
    name: 'Timor-Leste',
  },
  {
    cca2: 'gf',
    flag: 'https://flagcdn.com/gf.svg',
    idd: '594',
    name: 'French Guiana',
  },
  {
    cca2: 'ly',
    flag: 'https://flagcdn.com/ly.svg',
    idd: '218',
    name: 'Libya',
  },
  {
    cca2: 'lb',
    flag: 'https://flagcdn.com/lb.svg',
    idd: '961',
    name: 'Lebanon',
  },
  {
    cca2: 'kz',
    flag: 'https://flagcdn.com/kz.svg',
    idd: '76',
    name: 'Kazakhstan',
  },
  {
    cca2: 'gi',
    flag: 'https://flagcdn.com/gi.svg',
    idd: '350',
    name: 'Gibraltar',
  },
  {
    cca2: 'xk',
    flag: 'https://flagcdn.com/xk.svg',
    idd: '383',
    name: 'Kosovo',
  },
  {
    cca2: 'gb',
    flag: 'https://flagcdn.com/gb.svg',
    idd: '44',
    name: 'United Kingdom',
  },
  {
    cca2: 'tv',
    flag: 'https://flagcdn.com/tv.svg',
    idd: '688',
    name: 'Tuvalu',
  },
  {
    cca2: 'nf',
    flag: 'https://flagcdn.com/nf.svg',
    idd: '672',
    name: 'Norfolk Island',
  },
  {
    cca2: 'kg',
    flag: 'https://flagcdn.com/kg.svg',
    idd: '996',
    name: 'Kyrgyzstan',
  },
  {
    cca2: 'hu',
    flag: 'https://flagcdn.com/hu.svg',
    idd: '36',
    name: 'Hungary',
  },
  {
    cca2: 'fk',
    flag: 'https://flagcdn.com/fk.svg',
    idd: '500',
    name: 'Falkland Islands',
  },
  {
    cca2: 'fr',
    flag: 'https://flagcdn.com/fr.svg',
    idd: '33',
    name: 'France',
  },
  {
    cca2: 'lk',
    flag: 'https://flagcdn.com/lk.svg',
    idd: '94',
    name: 'Sri Lanka',
  },
  {
    cca2: 'yt',
    flag: 'https://flagcdn.com/yt.svg',
    idd: '262',
    name: 'Mayotte',
  },
  {
    cca2: 'eg',
    flag: 'https://flagcdn.com/eg.svg',
    idd: '20',
    name: 'Egypt',
  },
  {
    cca2: 'mk',
    flag: 'https://flagcdn.com/mk.svg',
    idd: '389',
    name: 'North Macedonia',
  },
  {
    cca2: 'th',
    flag: 'https://flagcdn.com/th.svg',
    idd: '66',
    name: 'Thailand',
  },
  {
    cca2: 'ls',
    flag: 'https://flagcdn.com/ls.svg',
    idd: '266',
    name: 'Lesotho',
  },
  {
    cca2: 'sl',
    flag: 'https://flagcdn.com/sl.svg',
    idd: '232',
    name: 'Sierra Leone',
  },
  {
    cca2: 'lr',
    flag: 'https://flagcdn.com/lr.svg',
    idd: '231',
    name: 'Liberia',
  },
  {
    cca2: 'be',
    flag: 'https://flagcdn.com/be.svg',
    idd: '32',
    name: 'Belgium',
  },
  {
    cca2: 'fm',
    flag: 'https://flagcdn.com/fm.svg',
    idd: '691',
    name: 'Micronesia',
  },
  {
    cca2: 'gq',
    flag: 'https://flagcdn.com/gq.svg',
    idd: '240',
    name: 'Equatorial Guinea',
  },
  {
    cca2: 'im',
    flag: 'https://flagcdn.com/im.svg',
    idd: '44',
    name: 'Isle of Man',
  },
  {
    cca2: 'cr',
    flag: 'https://flagcdn.com/cr.svg',
    idd: '506',
    name: 'Costa Rica',
  },
  {
    cca2: 'de',
    flag: 'https://flagcdn.com/de.svg',
    idd: '49',
    name: 'Germany',
  },
  {
    cca2: 'mr',
    flag: 'https://flagcdn.com/mr.svg',
    idd: '222',
    name: 'Mauritania',
  },
  {
    cca2: 'ch',
    flag: 'https://flagcdn.com/ch.svg',
    idd: '41',
    name: 'Switzerland',
  },
  {
    cca2: 'va',
    flag: 'https://flagcdn.com/va.svg',
    idd: '3906698',
    name: 'Vatican City',
  },
  {
    cca2: 'um',
    flag: 'https://flagcdn.com/um.svg',
    idd: '268',
    name: 'United States Minor Outlying Islands',
  },
  {
    cca2: 'vn',
    flag: 'https://flagcdn.com/vn.svg',
    idd: '84',
    name: 'Vietnam',
  },
  {
    cca2: 'ss',
    flag: 'https://flagcdn.com/ss.svg',
    idd: '211',
    name: 'South Sudan',
  },
  {
    cca2: 'za',
    flag: 'https://flagcdn.com/za.svg',
    idd: '27',
    name: 'South Africa',
  },
  {
    cca2: 'cd',
    flag: 'https://flagcdn.com/cd.svg',
    idd: '243',
    name: 'DR Congo',
  },
  {
    cca2: 'tt',
    flag: 'https://flagcdn.com/tt.svg',
    idd: '1868',
    name: 'Trinidad and Tobago',
  },
  {
    cca2: 'ml',
    flag: 'https://flagcdn.com/ml.svg',
    idd: '223',
    name: 'Mali',
  },
  {
    cca2: 'sj',
    flag: 'https://flagcdn.com/sj.svg',
    idd: '4779',
    name: 'Svalbard and Jan Mayen',
  },
  {
    cca2: 'dz',
    flag: 'https://flagcdn.com/dz.svg',
    idd: '213',
    name: 'Algeria',
  },
  {
    cca2: 'ps',
    flag: 'https://flagcdn.com/ps.svg',
    idd: '970',
    name: 'Palestine',
  },
  {
    cca2: 'sk',
    flag: 'https://flagcdn.com/sk.svg',
    idd: '421',
    name: 'Slovakia',
  },
  {
    cca2: 'mz',
    flag: 'https://flagcdn.com/mz.svg',
    idd: '258',
    name: 'Mozambique',
  },
  {
    cca2: 'ar',
    flag: 'https://flagcdn.com/ar.svg',
    idd: '54',
    name: 'Argentina',
  },
  {
    cca2: 'cz',
    flag: 'https://flagcdn.com/cz.svg',
    idd: '420',
    name: 'Czechia',
  },
  {
    cca2: 'fj',
    flag: 'https://flagcdn.com/fj.svg',
    idd: '679',
    name: 'Fiji',
  },
  {
    cca2: 'as',
    flag: 'https://flagcdn.com/as.svg',
    idd: '1684',
    name: 'American Samoa',
  },
  {
    cca2: 'gl',
    flag: 'https://flagcdn.com/gl.svg',
    idd: '299',
    name: 'Greenland',
  },
  {
    cca2: 'pl',
    flag: 'https://flagcdn.com/pl.svg',
    idd: '48',
    name: 'Poland',
  },
  {
    cca2: 'io',
    flag: 'https://flagcdn.com/io.svg',
    idd: '246',
    name: 'British Indian Ocean Territory',
  },
  {
    cca2: 'vu',
    flag: 'https://flagcdn.com/vu.svg',
    idd: '678',
    name: 'Vanuatu',
  },
  {
    cca2: 'sy',
    flag: 'https://flagcdn.com/sy.svg',
    idd: '963',
    name: 'Syria',
  },
  {
    cca2: 'aq',
    flag: 'https://flagcdn.com/aq.svg',
    idd: 'undefined',
    name: 'Antarctica',
  },
  {
    cca2: 'sr',
    flag: 'https://flagcdn.com/sr.svg',
    idd: '597',
    name: 'Suriname',
  },
  {
    cca2: 'ao',
    flag: 'https://flagcdn.com/ao.svg',
    idd: '244',
    name: 'Angola',
  },
  {
    cca2: 'bz',
    flag: 'https://flagcdn.com/bz.svg',
    idd: '501',
    name: 'Belize',
  },
  {
    cca2: 'gd',
    flag: 'https://flagcdn.com/gd.svg',
    idd: '1473',
    name: 'Grenada',
  },
  {
    cca2: 'me',
    flag: 'https://flagcdn.com/me.svg',
    idd: '382',
    name: 'Montenegro',
  },
  {
    cca2: 'hm',
    flag: 'https://flagcdn.com/hm.svg',
    idd: 'undefined',
    name: 'Heard Island and McDonald Islands',
  },
  {
    cca2: 'il',
    flag: 'https://flagcdn.com/il.svg',
    idd: '972',
    name: 'Israel',
  },
  {
    cca2: 'gw',
    flag: 'https://flagcdn.com/gw.svg',
    idd: '245',
    name: 'Guinea-Bissau',
  },
  {
    cca2: 'ni',
    flag: 'https://flagcdn.com/ni.svg',
    idd: '505',
    name: 'Nicaragua',
  },
  {
    cca2: 'mo',
    flag: 'https://flagcdn.com/mo.svg',
    idd: '853',
    name: 'Macau',
  },
  {
    cca2: 'ph',
    flag: 'https://flagcdn.com/ph.svg',
    idd: '63',
    name: 'Philippines',
  },
  {
    cca2: 'ci',
    flag: 'https://flagcdn.com/ci.svg',
    idd: '225',
    name: 'Ivory Coast',
  },
  {
    cca2: 'tw',
    flag: 'https://flagcdn.com/tw.svg',
    idd: '886',
    name: 'Taiwan',
  },
  {
    cca2: 'rw',
    flag: 'https://flagcdn.com/rw.svg',
    idd: '250',
    name: 'Rwanda',
  },
  {
    cca2: 'mf',
    flag: 'https://flagcdn.com/mf.svg',
    idd: '590',
    name: 'Saint Martin',
  },
  {
    cca2: 'sa',
    flag: 'https://flagcdn.com/sa.svg',
    idd: '966',
    name: 'Saudi Arabia',
  },
  {
    cca2: 'bf',
    flag: 'https://flagcdn.com/bf.svg',
    idd: '226',
    name: 'Burkina Faso',
  },
  {
    cca2: 'ne',
    flag: 'https://flagcdn.com/ne.svg',
    idd: '227',
    name: 'Niger',
  },
  {
    cca2: 'pa',
    flag: 'https://flagcdn.com/pa.svg',
    idd: '507',
    name: 'Panama',
  },
  {
    cca2: 'bq',
    flag: 'https://flagcdn.com/bq.svg',
    idd: '599',
    name: 'Caribbean Netherlands',
  },
  {
    cca2: 'cc',
    flag: 'https://flagcdn.com/cc.svg',
    idd: '61',
    name: 'Cocos (Keeling) Islands',
  },
  {
    cca2: 'kr',
    flag: 'https://flagcdn.com/kr.svg',
    idd: '82',
    name: 'South Korea',
  },
  {
    cca2: 'it',
    flag: 'https://flagcdn.com/it.svg',
    idd: '39',
    name: 'Italy',
  },
  {
    cca2: 'cf',
    flag: 'https://flagcdn.com/cf.svg',
    idd: '236',
    name: 'Central African Republic',
  },
  {
    cca2: 'sh',
    flag: 'https://flagcdn.com/sh.svg',
    idd: '290',
    name: 'Saint Helena, Ascension and Tristan da Cunha',
  },
  {
    cca2: 'ge',
    flag: 'https://flagcdn.com/ge.svg',
    idd: '995',
    name: 'Georgia',
  },
  {
    cca2: 'co',
    flag: 'https://flagcdn.com/co.svg',
    idd: '57',
    name: 'Colombia',
  },
  {
    cca2: 'km',
    flag: 'https://flagcdn.com/km.svg',
    idd: '269',
    name: 'Comoros',
  },
  {
    cca2: 'tj',
    flag: 'https://flagcdn.com/tj.svg',
    idd: '992',
    name: 'Tajikistan',
  },
  {
    cca2: 'ky',
    flag: 'https://flagcdn.com/ky.svg',
    idd: '1345',
    name: 'Cayman Islands',
  },
  {
    cca2: 'lu',
    flag: 'https://flagcdn.com/lu.svg',
    idd: '352',
    name: 'Luxembourg',
  },
  {
    cca2: 'ki',
    flag: 'https://flagcdn.com/ki.svg',
    idd: '686',
    name: 'Kiribati',
  },
  {
    cca2: 'ad',
    flag: 'https://flagcdn.com/ad.svg',
    idd: '376',
    name: 'Andorra',
  },
  {
    cca2: 'pn',
    flag: 'https://flagcdn.com/pn.svg',
    idd: '64',
    name: 'Pitcairn Islands',
  },
  {
    cca2: 'ru',
    flag: 'https://flagcdn.com/ru.svg',
    idd: '73',
    name: 'Russia',
  },
  {
    cca2: 'jm',
    flag: 'https://flagcdn.com/jm.svg',
    idd: '1876',
    name: 'Jamaica',
  },
  {
    cca2: 'cu',
    flag: 'https://flagcdn.com/cu.svg',
    idd: '53',
    name: 'Cuba',
  },
  {
    cca2: 'sn',
    flag: 'https://flagcdn.com/sn.svg',
    idd: '221',
    name: 'Senegal',
  },
  {
    cca2: 'bs',
    flag: 'https://flagcdn.com/bs.svg',
    idd: '1242',
    name: 'Bahamas',
  },
  {
    cca2: 'dj',
    flag: 'https://flagcdn.com/dj.svg',
    idd: '253',
    name: 'Djibouti',
  },
  {
    cca2: 'br',
    flag: 'https://flagcdn.com/br.svg',
    idd: '55',
    name: 'Brazil',
  },
  {
    cca2: 'sd',
    flag: 'https://flagcdn.com/sd.svg',
    idd: '249',
    name: 'Sudan',
  },
  {
    cca2: 'tn',
    flag: 'https://flagcdn.com/tn.svg',
    idd: '216',
    name: 'Tunisia',
  },
  {
    cca2: 'cy',
    flag: 'https://flagcdn.com/cy.svg',
    idd: '357',
    name: 'Cyprus',
  },
  {
    cca2: 'ma',
    flag: 'https://flagcdn.com/ma.svg',
    idd: '212',
    name: 'Morocco',
  },
  {
    cca2: 'ai',
    flag: 'https://flagcdn.com/ai.svg',
    idd: '1264',
    name: 'Anguilla',
  },
  {
    cca2: 'ae',
    flag: 'https://flagcdn.com/ae.svg',
    idd: '971',
    name: 'United Arab Emirates',
  },
  {
    cca2: 'eh',
    flag: 'https://flagcdn.com/eh.svg',
    idd: '2125288',
    name: 'Western Sahara',
  },
  {
    cca2: 'na',
    flag: 'https://flagcdn.com/na.svg',
    idd: '264',
    name: 'Namibia',
  },
  {
    cca2: 'bg',
    flag: 'https://flagcdn.com/bg.svg',
    idd: '359',
    name: 'Bulgaria',
  },
  {
    cca2: 'ke',
    flag: 'https://flagcdn.com/ke.svg',
    idd: '254',
    name: 'Kenya',
  },
  {
    cca2: 'sz',
    flag: 'https://flagcdn.com/sz.svg',
    idd: '268',
    name: 'Eswatini',
  },
  {
    cca2: 'ir',
    flag: 'https://flagcdn.com/ir.svg',
    idd: '98',
    name: 'Iran',
  },
  {
    cca2: 'la',
    flag: 'https://flagcdn.com/la.svg',
    idd: '856',
    name: 'Laos',
  },
  {
    cca2: 'do',
    flag: 'https://flagcdn.com/do.svg',
    idd: '1809',
    name: 'Dominican Republic',
  },
  {
    cca2: 'st',
    flag: 'https://flagcdn.com/st.svg',
    idd: '239',
    name: 'São Tomé and Príncipe',
  },
  {
    cca2: 'ee',
    flag: 'https://flagcdn.com/ee.svg',
    idd: '372',
    name: 'Estonia',
  },
  {
    cca2: 'us',
    flag: 'https://flagcdn.com/us.svg',
    idd: '1201',
    name: 'United States',
  },
  {
    cca2: 'af',
    flag:
      'https://upload.wikimedia.org/wikipedia/commons/5/5c/Flag_of_the_Taliban.svg',
    idd: '93',
    name: 'Afghanistan',
  },
  {
    cca2: 'ga',
    flag: 'https://flagcdn.com/ga.svg',
    idd: '241',
    name: 'Gabon',
  },
  {
    cca2: 'pf',
    flag: 'https://flagcdn.com/pf.svg',
    idd: '689',
    name: 'French Polynesia',
  },
  {
    cca2: 'kw',
    flag: 'https://flagcdn.com/kw.svg',
    idd: '965',
    name: 'Kuwait',
  },
  {
    cca2: 'pg',
    flag: 'https://flagcdn.com/pg.svg',
    idd: '675',
    name: 'Papua New Guinea',
  },
  {
    cca2: 'cl',
    flag: 'https://flagcdn.com/cl.svg',
    idd: '56',
    name: 'Chile',
  },
  {
    cca2: 'in',
    flag: 'https://flagcdn.com/in.svg',
    idd: '91',
    name: 'India',
  },
  {
    cca2: 'jo',
    flag: 'https://flagcdn.com/jo.svg',
    idd: '962',
    name: 'Jordan',
  },
  {
    cca2: 'ug',
    flag: 'https://flagcdn.com/ug.svg',
    idd: '256',
    name: 'Uganda',
  },
  {
    cca2: 'al',
    flag: 'https://flagcdn.com/al.svg',
    idd: '355',
    name: 'Albania',
  },
  {
    cca2: 'cn',
    flag: 'https://flagcdn.com/cn.svg',
    idd: '86',
    name: 'China',
  },
  {
    cca2: 'bi',
    flag: 'https://flagcdn.com/bi.svg',
    idd: '257',
    name: 'Burundi',
  },
  {
    cca2: 'az',
    flag: 'https://flagcdn.com/az.svg',
    idd: '994',
    name: 'Azerbaijan',
  },
  {
    cca2: 'bh',
    flag: 'https://flagcdn.com/bh.svg',
    idd: '973',
    name: 'Bahrain',
  },
  {
    cca2: 'si',
    flag: 'https://flagcdn.com/si.svg',
    idd: '386',
    name: 'Slovenia',
  },
  {
    cca2: 'zm',
    flag: 'https://flagcdn.com/zm.svg',
    idd: '260',
    name: 'Zambia',
  },
  {
    cca2: 'es',
    flag: 'https://flagcdn.com/es.svg',
    idd: '34',
    name: 'Spain',
  },
  {
    cca2: 'bj',
    flag: 'https://flagcdn.com/bj.svg',
    idd: '229',
    name: 'Benin',
  },
  {
    cca2: 'cv',
    flag: 'https://flagcdn.com/cv.svg',
    idd: '238',
    name: 'Cape Verde',
  },
  {
    cca2: 'bn',
    flag: 'https://flagcdn.com/bn.svg',
    idd: '673',
    name: 'Brunei',
  },
  {
    cca2: 'mh',
    flag: 'https://flagcdn.com/mh.svg',
    idd: '692',
    name: 'Marshall Islands',
  },
];
